<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>563a5b34-547e-4f8a-a8ee-985cdd78da9d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="13.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI.Vision.Server\AI.Vision.Server.csproj" />
  </ItemGroup>

</Project>
